const fs=require('fs');
const path='/mnt/data/patch_v33/script.js';
let s=fs.readFileSync(path,'utf8');
function rep(oldStr,newStr,label){ if(!s.includes(oldStr)){ console.error('not found',label); process.exit(1); } s=s.replace(oldStr,newStr); console.log('patched',label); }
rep(`function renderTables() {\n  const p = parcelData.find((x) => x.id === selectedParcelId);\n  const seasonSource = (document.getElementById('seasonSourceSel')?.value) || STATE.seasonSource || 's1';\n`, `function renderTables() {\n  let p = (parcelData || []).find((x) => String(x?.id) === String(selectedParcelId));\n  if(!p){\n    p = (parcelData || []).find(x=>x && x.id);\n    if(p){\n      selectedParcelId = String(p.id);\n      try{ const sel=document.getElementById('parcelSelect'); if(sel) sel.value=selectedParcelId; }catch(_e){}\n    }else{\n      console.warn('renderTables: seçili parsel bulunamadı ve parcelData boş.');\n      return;\n    }\n  }\n  const seasonSource = (document.getElementById('seasonSourceSel')?.value) || STATE.seasonSource || 's1';\n`, 'renderTables guard');
rep(`    if(parcelLayer) candidates.push(parcelLayer);\n    if(customUserLayer) candidates.push(customUserLayer);\n`, `    if(parcelLayer) candidates.push(parcelLayer);\n    if(customUserLayer) candidates.push(customUserLayer);\n    if(window.__PENDING_DRAWING_LAYER) candidates.push(window.__PENDING_DRAWING_LAYER);\n`, 'focus candidates');
rep(`    if(targetLayer){\n      const b = targetLayer.getBounds ? targetLayer.getBounds() : null;\n      if(b && b.isValid()) map.fitBounds(b.pad(0.35), { animate:true });\n      try{ targetLayer.openPopup(); }catch(_e){}\n    }\n`, `    if(targetLayer){\n      const b = targetLayer.getBounds ? targetLayer.getBounds() : null;\n      if(b && b.isValid()) map.fitBounds(b.pad(0.35), { animate:true });\n      else if(typeof targetLayer.getLatLng === 'function') map.setView(targetLayer.getLatLng(), Math.max(map.getZoom() || 13, 14), { animate:true });\n      try{ targetLayer.openPopup(); }catch(_e){}\n    }else if(window.__PENDING_MARKERS_BY_ID && window.__PENDING_MARKERS_BY_ID[String(pid)]){\n      const marker = window.__PENDING_MARKERS_BY_ID[String(pid)];\n      try{ map.setView(marker.getLatLng(), Math.max(map.getZoom() || 13, 14), { animate:true }); marker.openPopup(); }catch(_e){}\n    }\n`, 'focus marker');
rep(`  try{\n    (parcelData || []).filter(p=>!!p?.frontend_custom && !!p?.feature).forEach(p=> customUserLayer.addData(p.feature));\n    syncAllCustomParcelLayerBindings();\n  }catch(_e){}\n\n  map.on('click', (e)=>{\n`, `  try{\n    (parcelData || []).filter(p=>!!p?.frontend_custom && !!p?.feature).forEach(p=> customUserLayer.addData(p.feature));\n    syncAllCustomParcelLayerBindings();\n  }catch(_e){}\n\n  // v33: Gerçek GeoJSON'u henüz çizilmemiş resmi parseller için\n  // haritada seçilebilir “çizim bekleyen parsel” işaretleri.\n  let pendingDrawingLayer = L.layerGroup().addTo(map);\n  window.__PENDING_DRAWING_LAYER = pendingDrawingLayer;\n  window.__PENDING_MARKERS_BY_ID = {};\n\n  map.on('click', (e)=>{\n`, 'pending layer');
rep(`let activeVillageFilter = '';\nlet showDryParcels = true;\nlet showIrrigatedParcels = true;\nlet showVillageBoundary = false;\nlet showReservoirArea = false;\n`, `let activeVillageFilter = '';\nlet showAllParcelsLayer = true;\nlet showDryParcels = true;\nlet showIrrigatedParcels = true;\nlet showVillageBoundary = false;\nlet showReservoirArea = false;\n`, 'show var');
const marker='const updateMapLayerStatusV30 = (count, village)=>{\n';
if(!s.includes(marker)){ console.error('status marker missing'); process.exit(1); }
s=s.replace(marker, fs.readFileSync('/mnt/data/patch_v33/snippet_pending.js.txt','utf8')+marker);
const start=s.indexOf('const updateMapLayerStatusV30 = (count, village)=>{');
const end=s.indexOf('const applyMapFilters', start);
if(start<0||end<0){ console.error('status block bounds failed',start,end); process.exit(1); }
s=s.slice(0,start)+fs.readFileSync('/mnt/data/patch_v33/snippet_status.js.txt','utf8')+s.slice(end);
rep(`    const fc = { type: 'FeatureCollection', features: filtered };\n    updateMapLayerStatusV30(filtered.length, activeVillageFilter);\n    parcelLayer.clearLayers();\n    parcelLayer.addData(fc);\n    try{ updateStyles(); }catch(_e){}\n    refreshVillageBoundary(filtered, activeVillageFilter);\n    renderReservoirAreaLayer();\n`, `    const fc = { type: 'FeatureCollection', features: filtered };\n    parcelLayer.clearLayers();\n    parcelLayer.addData(fc);\n    let pendingCount = 0;\n    try{ pendingCount = renderPendingDrawingMarkersV33(activeVillageFilter); }catch(_e){ pendingCount = 0; }\n    updateMapLayerStatusV30(filtered.length, activeVillageFilter, pendingCount);\n    try{ updateStyles(); }catch(_e){}\n    refreshVillageBoundary(filtered, activeVillageFilter);\n    renderReservoirAreaLayer();\n`, 'apply pending');
rep(`    if(chkParcels){\n      chkParcels.addEventListener('change', ()=>{\n        try{\n          if(chkParcels.checked){ if(!map.hasLayer(parcelLayer)) parcelLayer.addTo(map); }\n          else { if(map.hasLayer(parcelLayer)) map.removeLayer(parcelLayer); }\n          applyMapFilters({ village: selVillage ? selVillage.value : activeVillageFilter, fit:false });\n        }catch(_e){}\n      });\n    }\n`, `    if(chkParcels){\n      chkParcels.addEventListener('change', ()=>{\n        try{\n          showAllParcelsLayer = !!chkParcels.checked;\n          if(showAllParcelsLayer){\n            if(!map.hasLayer(parcelLayer)) parcelLayer.addTo(map);\n            if(pendingDrawingLayer && !map.hasLayer(pendingDrawingLayer)) pendingDrawingLayer.addTo(map);\n          }else {\n            if(map.hasLayer(parcelLayer)) map.removeLayer(parcelLayer);\n            try{ pendingDrawingLayer?.clearLayers(); if(map.hasLayer(pendingDrawingLayer)) map.removeLayer(pendingDrawingLayer); }catch(_e){}\n          }\n          applyMapFilters({ village: selVillage ? selVillage.value : activeVillageFilter, fit:false });\n        }catch(_e){}\n      });\n    }\n`, 'checkbox');
rep(`  function updateStyles() {\n    try{ parcelLayer.setStyle(style); }catch(_e){}\n    try{ if(customUserLayer){ customUserLayer.setStyle(customUserLayer.options.style); } }catch(_e){}\n    try{ applyRoleLayerVisibility(); }catch(_e){}\n  }\n`, `  function updateStyles() {\n    try{ parcelLayer.setStyle(style); }catch(_e){}\n    try{ if(customUserLayer){ customUserLayer.setStyle(customUserLayer.options.style); } }catch(_e){}\n    try{ renderPendingDrawingMarkersV33(activeVillageFilter); }catch(_e){}\n    try{ applyRoleLayerVisibility(); }catch(_e){}\n  }\n`, 'updateStyles');
s=s.replaceAll('[v31 GeoJSON bundle]', '[v33 GeoJSON bundle]').replaceAll('[v31 GeoJSON]', '[v33 GeoJSON]').replaceAll('[v32 GeoJSON]', '[v33 GeoJSON]');
fs.writeFileSync(path,s,'utf8');
let htmlPath='/mnt/data/patch_v33/index.html'; let html=fs.readFileSync(htmlPath,'utf8'); html=html.replace(/script\.js\?v=\d+/g,'script.js?v=330'); fs.writeFileSync(htmlPath,html,'utf8');
let cssPath='/mnt/data/patch_v33/style.css'; let css=fs.readFileSync(cssPath,'utf8'); const add=`\n\n/* v33: Çizim bekleyen resmi parsel işaretleri */\n.pending-parcel-marker{ background: transparent !important; border:0 !important; }\n.pending-parcel-marker .parcel-badge{ border-color: rgba(245,158,11,.55); background: rgba(255,251,235,.96); color:#7c2d12; }\n.pending-parcel-marker .parcel-badge .dot{ background:#f59e0b; }\n.pending-parcel-marker .parcel-badge.orchard .dot{ background:#23a559; }\n.pending-parcel-marker .parcel-badge.selected{ background:rgba(219,234,254,.98); border-color:#2563eb; color:#1e3a8a; box-shadow:0 0 0 3px rgba(37,99,235,.18),0 4px 12px rgba(30,64,175,.26); }\n.pending-pop .source-file{font-size:10px; line-height:1.2;}\n`;
if(!css.includes('v33: Çizim bekleyen resmi parsel işaretleri')) fs.writeFileSync(cssPath,css+add,'utf8');
fs.writeFileSync('/mnt/data/patch_v33/GUNCELLEME_NOTU_2026-04-25_v33_KEMERHISAR_BOS_ISARET_FIX.txt','Kemerhisar için çizim bekleyen P122-P156 parsel işaretleri haritada görünür hale getirildi; gerçek GeoJSON olmayan kayıtlar artık seçilebilir marker olarak gösterilir. renderTables seçili parsel bulunamadığında çökmeyecek şekilde korumaya alındı. script.js?v=330.\n','utf8');
